practices/pratices/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^todolist/', include('todolist.urls',namespace="todolist")),
    url(r'^admin/', admin.site.urls),
]

practices/todolist/urls.py
from django.conf.urls import url
import django.contrib.auth.views as auth_view
from . import views

app_name = 'todolist'

urlpatterns = [

	url(r'^$', views.home, name='home'),
	url(r'^index$', views.index, name='index'),
	
	
	url(r'^login/', auth_view.login, {'template_name': 'login.html'}, name='login'),
	url(r'^logout/$',views.logout ,name='logout'),
	url(r'^register/', views.register, name='register'),
	url(r'^profile/', views.profile, name='profile'),
	url(r'^profile_submit/', views.profile_submit, name='profile_submit'),

	url(r'^complete/$', views.complete,name='complete'),
	url(r'^expired/$', views.expired, name='expired'),
	url(r'^tobedoned/$', views.tobedoned, name='tobedoned'),
	
	url(r'^(?P<tobedone_id>[0-9]+)/$', views.detail, name='detail'),
	
	url(r'^add/$', views.add,name='add'),
	url(r'^add_submit/$', views.add_submit,name='add_submit'),
	url(r'^update_submit/$', views.update_submit,name='update_submit'),
	url(r'^delete_submit/$', views.delete_submit,name='delete_submit'),
]

practices/todolist/models.py
from django.db import models

# Create your models here.

from django.utils import timezone
import datetime

class tobedone(models.Model):
    
	def __str__(self):              
		return self.title
	def exp(self):
		return self.deadline >= timezone.now()

	user=models.CharField(max_length=200)
	title= models.CharField(max_length=200)
	detail= models.TextField(blank=True)
	deadline = models.DateField()
	pub_date = models.DateTimeField('date published')
	finish= models.BooleanField(default=False)
        

practices/todolist/views.py
from django.shortcuts import get_object_or_404,render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from .models import tobedone
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib import auth  
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'home.html', {'username': request.user.username})
	
def register(request):
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('todolist:login'))
    return render(request, 'register.html', {'form': form})



@login_required
def index(request):
	#latest_task = tobedone.objects.order_by('-pub_date')[:5]
	latest_task=tobedone.objects.filter(user=request.user.username)
	context = {'latest_task': latest_task}
	return render(request,'index.html', context)
	
@login_required
def detail(request, tobedone_id):
    t = get_object_or_404(tobedone, pk=tobedone_id)
    return render(request, 'detail.html', {'tobedone': t})
	
@login_required
def add(request):
    return render(request,'add.html',{'currenttime':timezone.now()})

@login_required
def add_submit(request):
    tobedone.objects.create(user=request.POST.get('user',''),title=request.POST.get('title',''),detail=request.POST.get('detail',''),deadline=request.POST.get('deadline',''),finish=request.POST.get('finish','') ,pub_date=timezone.now())
    return HttpResponseRedirect(reverse('todolist:index'))
	
@login_required	
def update_submit(request):
	u=tobedone.objects.filter(id=request.POST.get('id',''))
	u.update(title=request.POST.get('title',''),detail=request.POST.get('detail',''),deadline=request.POST.get('deadline',''),finish=request.POST.get('finish',''))
	return HttpResponseRedirect(reverse('todolist:index'))

@login_required	
def delete_submit(request):
	t=tobedone.objects.get(pk=request.POST.get('id',''))
	t.delete()
	return HttpResponseRedirect(reverse('todolist:index'))

@login_required
def complete(request):
	completed_task=tobedone.objects.filter(finish=True).filter(user=request.user.username)
	return render(request,'complete.html',{'completed_task': completed_task})
	
@login_required
def expired(request):
	#ex=tobedone.objects.get(tobedone=True)
	ex=tobedone.objects.filter(deadline__lte=timezone.now()).filter(user=request.user.username)
	#ex=tobedone.objects.all()
	return render(request,'expired.html',{'expired_task': ex})

@login_required
def tobedoned(request):
	tobedoned_task=tobedone.objects.filter(finish=False).filter(user=request.user.username)
	return render(request,'tobedone.html',{'tobedoned_task': tobedoned_task})

@login_required	
def logout(request):
    auth.logout(request)
    return render(request,'home.html')

@login_required	
def profile(request):
    return render(request,'profile.html')

@login_required	
def profile_submit(request):
	user=User.objects.get(username=request.POST.get('user',''))
	user.set_password(request.POST.get('password',''))
	user.save()
	user=User.objects.filter(username=request.POST.get('user',''))
	user.update(first_name=request.POST.get('first_name',''),last_name=request.POST.get('last_name',''),email=request.POST.get('email',''))
	return HttpResponseRedirect(reverse('todolist:index'))
	

practices/templates/add.html
<h1>add events</h1>

<form action="{% url 'todolist:add_submit' %}" method="post">
{% csrf_token %}

<label for="title">title：</label>
<input type='text' name="title" value=""><br>

<label for="detail">detail：</label>
<input type='text' name='detail' value=""><br>

<label for="deadline">deadlene:</label>
<input type='date' name='deadline' value={{currenttime|date:"Y-m-d"}}><br>

<label for="finish">finished:</label>

<input type="radio" name="finish" value=True>finish
<input type="radio" name="finish" value=""  checked="true">Not yet

<input type="hidden" name="user" value="{{request.user}}">

<p><input type="submit" value="add event" /></p>
</form>

practices/templates/complete.html
<p>completed task</p>
{% if completed_task %}
    <ul>
    {% for tobedone in completed_task %}
        <li><a href="{% url 'todolist:detail' tobedone.id %}">{{ tobedone.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No task has been done.</p>
{% endif %}

practices/templates/detail.html
<body>
<form action="{% url 'todolist:update_submit' %}" method="post">
{% csrf_token %}
<p>user:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ tobedone.user }}</p>
<p>taskname:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type='text' name='title' value={{tobedone.title}}></p>
<p>id:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ tobedone.id }}</p>
<p>detail:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type='text' name='detail' value={{tobedone.detail }}></p>
<p>deadline:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type='date' name='deadline' value={{tobedone.deadline|date:"Y-m-d"}}></p>
<p>pub_date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ tobedone.pub_date }}
<p>finish:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ tobedone.finish }}{% if tobedone.finish %}<input type="radio" name="finish" value="1" checked={{tobedone.finish }}>done<input type="radio" name="finish" value="0">not yet</p>{% else %}<input type="radio" name="finish" value="1" >done<input type="radio" name="finish" value="0" checked=True>not yet</p>{% endif %}
<br></br>
<input type='hidden' name='id' value={{ tobedone.id }}>	<input type="submit" name="update" value="update" />
<br></br>
</form>

<form action="{% url 'todolist:delete_submit' %}" method="post">
{% csrf_token %}
<input type='hidden' name='id' value='{{ tobedone.id }}'><input type="submit" name="delete" value="delete" />
</form>
</body>

practices/templates/expired.html
<p>expire task</p>
{% if expired_task %}
    <ul>
    {% for tobedone in expired_task %}
		<li><a href="{% url 'todolist:detail' tobedone.id %}">{{ tobedone.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No expired  task.</p>
{% endif %}

practices/templates/home.html
<html>
    <head>
        <title>todolist</title>
    </head>
    <body>
        <h2>todolist</h2>
        {% if request.user.is_authenticated %}
            <p>{{request.user}} 您已經登入囉</p>
			
            <a href="{% url 'todolist:index' %}">todolist</a>
			<br></br>
			<a href="{% url 'todolist:logout' %}">logout</a>
			<br></br>
			<a href="{% url 'todolist:profile' %}">profile</a>
        {% else %}
            <p>您尚未登入喔</p>
			<p><a href="{% url 'todolist:login' %}">login</a></p>
			<p><a href="{% url 'todolist:register' %}">register</a></p>
        {% endif %}
    </body>
</html>

practices/templates/index.html
<h1>todolist</h1>

<p>user:	<a href="{% url 'todolist:profile'%}">{{request.user}}</a></p>

<p>options</p>
<ul>
	<li><a href="{% url 'todolist:add'%}">add events</a></li>
	<li><a href="{% url 'todolist:profile'%}">profile</a></li>
	<li><a href="{% url 'todolist:logout' %}">logout</a></li>
	<li><a href="{% url 'todolist:register'%}">register</a></li>
</ul>

<p>events</p>
<ul>
	<li><a href="{% url 'todolist:tobedoned'%}">tobedone</a></li>
	<li><a href="{% url 'todolist:complete'%}">completed events</a></li>
	<li><a href="{% url 'todolist:expired'%}">expired events</a></li>
</ul>



<p>all events</p>
{% if latest_task %}
    <ul>
    {% for tobedone in latest_task %}
			<li><a href="{% url 'todolist:detail' tobedone.id %}">{{ tobedone.title }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No task.
{% endif %}

practices/templates/login.html
<h1>Login</h1>
  <form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

practices/templates/profile.html
<h1>profile</h1>
	<form action="{% url 'todolist:profile_submit' %}" method="post">
		{% csrf_token %}

		<label for="title">username：</label>
		<input type='text' name="username" value={{request.user.username}}><br>

		<label for="detail">first name：</label>
		<input type='text' name='first_name' value={{request.user.first_name}}><br>

		<label for="deadline">last name:</label>
		<input type='text' name='last_name' value={{request.user.last_name}}><br>

		<label for="deadline">email:</label>
		<input type='text' name='email' value={{request.user.email}}><br>
		
		<label for="deadline">password:</label>
		<input type='text' name='password' ><br>

		<input type="hidden" name="user" value="{{request.user}}">

		<p><input type="submit" value="update profile" /></p>
	
	</form>

practices/templates/register.html
<h1>Register</h1>
  <form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

practices/templates/tobedone.html
<p>tobedoned task</p>
{% if tobedoned_task %}
    <ul>
    {% for tobedone in tobedoned_task %}
        <li><a href="{% url 'todolist:detail' tobedone.id %}">{{ tobedone.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tobedoned  task.</p>
{% endif %}